/** @noSelfInFile */

declare function GetAllCollisions(): number[];
declare function CreateCollisionBox(x: number, y: number, z: number, bx: number, by: number, bz: number): number;
declare function CreateCollisionBox(x: number, y: number, z: number, bx: number, by: number, bz: number, bVisible: boolean): number;
declare function CreateCollisionSphere(x: number, y: number, z: number, radius: number): number;
declare function CreateCollisionSphere(x: number, y: number, z: number, radius: number, bVisible: boolean): number;
declare function DestroyCollision(collision: number): void;
declare function SetCameraShakeLocation(XAmp: number, XFreq: number, YAmp: number, YFreq: number, ZAmp: number, ZFreq: number): void;
declare function GetPlayerWeapon(player: number): number;
declare function GetPlayerWeapon(player: number, weaponSlot: boolean): number;
declare function StopCameraFade(): void;
declare function ShowWeaponHUD(show: boolean): void;
declare function DrawCircle3D(x: number, y: number, z: number, radius: number, r: number, g: number, b: number): number;
declare function DrawCircle3D(x: number, y: number, z: number): number;
declare function DrawRect(sX: number, sY: number, sW: number, sH: number): number;
declare function DrawRect(sX: number, sY: number, sW: number, sH: number, r: number, g: number, b: number): number;
declare function GetPackageName(): string;
declare function GetPlayerBoneNames(): string;
declare function GetScreenSize(): number;
//declare function RGBA(r: number, g: number, b: number, a: number): void;
declare function PlayCameraShake(duration: number): void;
declare function PlayCameraShake(duration: number, blendInTime: number, blendOutTime: number, scale: number): void;
declare function SetWaypoint(slot: number, name: string, x: number, y: number, z: number): number;
//declare function GetChatLocation(): number;
declare function SetCameraShakeFOV(FOVAmp: number, FOVFreq: number): void;
declare function SetTextBoxAlignment(textId: number, x: number, y: number): void;
declare function ShowHealthHUD(show: boolean): void;
declare function ShowMouseCursor(bShow: boolean): void;
declare function ScreenToWorld(x: number, y: number): number;
declare function DrawBox(sX: number, sY: number, sW: number, sH: number): void;
declare function DrawBox(sX: number, sY: number, sW: number, sH: number, thickness: number, r: number, g: number, b: number): void;
declare function SetSunRadius(radius: number): void;
declare function GetAllPlayersInBox(x: number, y: number, z: number, bx: number, by: number, bz: number): number[];
declare function GetAllPlayersInBox(x: number, y: number, z: number, bx: number, by: number, bz: number, bIncludeSelf: boolean): number[];
declare function SetMoonShine(shine: number): void;
declare function GetPlayerRotationRate(): number;
//declare function GetMouseLocation(): void;
//declare function GetPlayerCameraUpVector(): number;
declare function SetTextBoxText(textid: number, text: string): void;
declare function CreateTextBox(x: number, y: number, text: string, justification: any): number;
declare function CreateTextBox(x: number, y: number, text: string): number;
declare function SetStarsBrightness(brightness: number): void;
//declare function DrawTexture(): void;
//declare function WorldToScreen(x: number, y: number, z: number): void;
declare function IsChatFocus(): boolean;
declare function SetSunAzimuth(azimuth: number): void;
declare function CreateSound(SoundFile: string): number;
declare function CreateSound(SoundFile: string , bLoop: boolean): number;
//declare function GetPlayerMovementMode(player: number): void;
declare function ImportPackage(PackageName: string): void;
declare function SetOceanColor(HexColor: string): void;
declare function GetMouseInputDelta(): number;
declare function IsPlayerReloading(player: number): boolean;
declare function IsPlayerAiming(player: number): boolean;
declare function GetPlayerMovementSpeed(player: number): number;
declare function IsPlayerInVehicle(player: number): boolean;
declare function IsPlayerInVehicle(): boolean;
declare function SetDrawScale(sx: number, sy: number): void;
declare function SetSkyRotationSpeed(speed: number): void;
//declare function GetAllSounds(): void;
declare function LineTrace(sX: number, sY: number, sZ: number, eX: number, eY: number, eZ: number): number;
declare function LineTrace(sX: number, sY: number, sZ: number, eX: number, eY: number, eZ: number, complex: number): number;
declare function ShowChat(show: boolean): void;
declare function SetTextBoxAnchors(textid: number, minX: number, minY: number, maxX: number, maxY: number): void;
declare function AddFunctionExport(ExportName: string, ExportFunction: any): void;
//declare function CreateSound3D(SoundFile, x: number, y: number, z: number [, radius, bLoop]): void;
//declare function SetPlayerOutline(player: number, [, bEnable]): void;
//declare function IsValidSound(sound): boolean;
//declare function SetSoundVolume(sound, volume: number): void;
declare function SetObjectCastShadow(object: number, bEnable: boolean): void;
declare function DrawLine(sX: number, sY: number, eX: number, eY: number): number;
declare function DrawLine(sX: number, sY: number, eX: number, eY: number, thickness: number, r: number, g: number, b: number): number;
declare function SetFogDensity(density: number): void;
//declare function GetPlayerBoneLocation(player: number, BoneName: string [, BoneSpace]): void;
//declare function EnableObjectHitEvents(object [, bEnable]): void;
declare function GetSoundCount(): number;
declare function DestroyTextBox(textid: number): void;
//declare function GetInputAxisValue(AxisName: string): void;
declare function AddPlayerChat(message: string): void;
//declare function DestroySound(sound): void;
//declare function HexToRGBA(HexColor: string): void;
declare function Random(): number;
declare function Random(min: number, max: number): number;
//declare function RGB(r: number, g: number, b: number): void;
//declare function RGB(r: number, g: number, b: number, a: number): void;
declare function SetPlayerRotationRate(RotationRate: number): void;
//declare function GetPlayerCameraLocation(): void;
declare function GetAllCollisions(): number[];
declare function GetTerrainHeight(sX: number, sY: number, sZ: number): number;
declare function Base64Decode(base64: string): string;
declare function GetGameVersion(): string;
//declare function GetPlayerCameraRightVector(): void;
declare function SetObjectOutline(object: number): void;
declare function SetObjectOutline(object: number, bEnable: boolean): void;
declare function SetDrawColor(HexColor: string): void;
declare function DrawLine3D(sX: number, sY: number, sZ: number, eX: number, eY: number, eZ: number): void;
declare function DrawLine3D(sX: number, sY: number, sZ: number, eX: number, eY: number, eZ: number, r: number, g: number, b: number): void;
declare function SetChatLocation(x: number, y: number): void;
//declare function SetObjectEditable(object: number, EditMode): void;
//declare function SetCameraShakeRotation(PitchAmp, PitchFreq, YawAmp, YawFreq, RollAmp, RollFreq): void;
declare function DrawSolidBox3D(x: number, y: number, z: number, eX: number, eY: number, eZ: number, HexColor: string): number;
declare function SetSkyLightIntensity(intensity: number): void;
declare function GetTextSize(text: string): number;
declare function GetTextSize(text: string, scale: number): number;
//declare function GetPlayerCameraRotation(): void;
declare function GetStreamedLights(): number[];
declare function DrawText(x: number, y: number, text: string): number;
declare function SetTime(time: number): void;
declare function IsMouseCursorEnabled(): boolean;
declare function GetLightCount(): number;
declare function SetMoonRadius(radius: number): void;
//declare function DeprojectMouseLocationToWorld(): void;
declare function SetMoonLightIntensity(intensity: number): void;
declare function SetSunLightIntensity(intensity: number): void;
declare function SetSunShine(shine: number): void;
declare function GetPing(): number;
//declare function GetNetworkStats(): void;
//declare function GetStreamedNPC(): void;
//declare function GetNPCLocation(npc: number): void;
declare function GetNPCCount(): number;
//declare function SetInputMode(InputMode): void;
//declare function GetLightLocation(light: number): void;
declare function SetNPCOutline(npc: number): void;
declare function SetNPCOutline(npc: number, bEnable: boolean): void;
declare function GetObjectScale(object: number): number;
//declare function SetWeather(weather): void;
declare function GetObjectCount(): number;
declare function GetTime(): number;
//declare function GetObjectBoundingBox(object: number): void;
declare function GetObjectSize(object: number): number;
declare function GetObjectModelCount(): number;
//declare function GetObjectModel(object: number): void;
declare function AddEvent(EventName: string, LuaFunction: any): void;
//declare function GetPickupLocation(pickupid: number): void;
declare function GetPickupCount(): number;
//declare function GetPlayerLocation(player: number): void;
declare function GetAllPlayersInSphere(x: number, y: number, z: number, radius: number): number[];
declare function GetAllPlayersInSphere(x: number, y: number, z: number, radius: number, bIncludeSelf: boolean): number[];
declare function GetStreamedObjects(): number[];
declare function GetStreamedObjects(bGetAttached: boolean): number[];
declare function IsPlayerDead(player: number): boolean;
declare function CallRemoteEvent(player: number, EventName: string, ...luaArgs: any): void;
declare function AddRemoteEvent(RemoteEventName: string, LuaFunction: any): void;
//declare function GetObjectModelGroup(model): void;
//declare function GetObjectRotation(object): void;
declare function CallEvent(EventName: string, ...userArgs: any): void;
declare function GetPlayerCount(): number;
declare function GetStreamedPlayers(): number[];
//declare function GetPlayerHeading(player: number): void;
declare function IsValidPlayer(player: number): boolean;
declare function GetStreamedPickups(): number[];
declare function StopCameraShake(): void;
declare function StopCameraShake(bImmediate: boolean): void;
//declare function GetPlayerArmor(player: number): number;
declare function StartCameraFade(FromAlpha: number, ToAlpha: number, Duration: number): void;
declare function StartCameraFade(FromAlpha: number, ToAlpha: number, Duration: number, hexColor: string): void;
declare function SetSkySaturation(saturation: number): void;
declare function GetMouseHitEntity(): number;
declare function GetPlayerFOV(): number;
declare function SetPlayerCameraRotation(x: number, y: number, z: number): void;
declare function GetDistance3D(x: number, y: number, z: number, x2: number, y2: number, z2: number): number;
declare function GetTimeSeconds(): number;
//declare function VectorToRotation(x: number, y: number, z: number): void;
declare function SetPlayerCameraLocation(x: number, y: number, z: number): void;
declare function SetPlayerFOV(fov: number): void;
declare function GetPlayerCameraViewDistance(): number;
declare function SetObjectEditorSpeed(speed: number): void;
//declare function InvokeDamageFX(value): void;
declare function IsPlayerInMainMenu(): boolean;
declare function GetDeltaSeconds(): number;
declare function GetDistanceSquared3D(x: number, y: number, z: number, x2: number, y2: number, z2: number): number;
declare function SetPlayerCameraViewDistance(distance: number): void;
declare function DrawPoint3D(x: number, y: number, z: number, pointSize: number, r: number, g: number, b: number): number;
declare function DrawPoint3D(x: number, y: number, z: number): number;
//declare function NormalizeVector(x: number, y: number, z: number): void;
declare function GetTickCount(): number;
declare function IsPlayerTalking(player: number): boolean;
declare function GetPlayerHealth(player: number): number;
//declare function RotationToVector(x: number, y: number, z: number): void;
declare function GetObjectMass(object: number): number;
//declare function GetMouseHitLocation(): void;
//declare function SetSoundPitch(sound, Pitch: number): void;
//declare function GetSoundVolume(sound): void;
//declare function SetSoundFadeOut(sound, Duration, VolumeLevel): void;
declare function GetDistance2D(x: number, y: number, x2: number, y2: number): number;
//declare function GetSoundPitch(sound): number;
declare function IsFloatNearlyZero(Value: number): boolean;
//declare function GetVehicleModel(vehicle: number): void;
//declare function GetSoundDuration(sound): number;
declare function GetText3DCount(): number;
//declare function GetVehicleLocation(vehicle: number): void;
declare function IsValidTimer(timer: number): boolean;
declare function CreateTimer(task: Function, interval: number, ...args: any[]): number;
//declare function GetVehicleRightVector(vehicle: number): void;
declare function PauseTimer(timer: number): void;
//declare function GetVehicleHoodRatio(vehicle: number): void;
//declare function GetVehicleDoorLocation(vehicle, door): void;
//declare function GetVehicleForwardVector(vehicle): void;
declare function IsVehicleHornActive(vehicle: number): boolean;
//declare function SetSoundFadeIn(sound [, Duration, VolumeLevel, StartTime]): void;
declare function IsVehicleInAir(vehicle: number): boolean;
//declare function GetVehicleWheelSteerAngle(vehicle, wheel): void;
//declare function GetVehicleEngineState(vehicle: number): void;
//declare function IsVehicleSeatOccupied(vehicle: number, seat): void;
declare function GetVehicleGear(vehicle: number): number;
declare function IsVehicleInWater(vehicle: number): boolean;
//declare function IsVehicleWheelInAir(vehicle: number, wheel): void;
declare function GetVehicleEngineRPM(vehicle: number): number;
declare function GetVehicleForwardSpeed(vehicle: number): number;
declare function GetAllTimers(): number[];
//declare function GetWebVisibility(web): void;
//declare function GetVehicleTrunkRatio(vehicle): void;
//declare function GetVehicleBoundingBox(vehicle): void;
//declare function LoadWebFile(web, File): void;
//declare function GetVehicleLightState(vehicle: number): void;
declare function GetAllWebUI(): number[];
declare function DestroyWebUI(web: number): void;
declare function SetWebVisibility(web: number, visibility: boolean): void;
declare function SetWebRotation(web: number, rx: number, ry: number, rz: number): void;
declare function ExecuteWebJS(web: number, Javascript: string): void;
//declare function GetText3DLocation(text3d: number): void;
declare function GetStreamedText3D(): number[];
//declare function GetVehicleWheelSurface(vehicle, wheel): void;
declare function GetVehicleVelocity(vehicle: number): number;
declare function GetStreamedVehicles(): number[];
declare function IsValidVehicle(vehicle: number): boolean;
//declare function GetVehicleRotation(vehicle: number): void;
declare function GetTimerCount(): number;
declare function GetTimerRemainingTime(timer: number): number;
declare function UnpauseTimer(timer: number): void;
declare function DestroyTimer(timer: number): void;
declare function CreateCountTimer(LuaFunction: any, Interval: number, Count: number): void;
declare function CreateCountTimer(LuaFunction: any, Interval: number, Count: number, userArgs: any[]): void;
declare function SetWebURL(web: number, URL: string): void;
declare function SetWebLocation(web: number, x: number, y: number): void;
declare function SetWebLocation(web: number, x: number, y: number, z: number): void;
declare function SetWebSize(web: number, width: number, height: number): void;
declare function GetVehicleCount(): number;
declare function SetWebAnchors(web: number, minX: number, minY: number, maxX: number, maxY: number): void;
declare function RandomFloat(): number;
declare function RandomFloat(Min: number, Max: number): number;
declare function GetVehicleHealth(vehicle: number): number;
//declare function GetVehicleUpVector(vehicle: number): void;
declare function SetWebAlignment(web: number, x: number, y: number): void;
declare function GetWebUICount(): number;
declare function SetIgnoreMoveInput(bIgnore: boolean): void;
declare function CreateWebUI3D(x: number, y: number, z: number, rx: number, ry: number, rz: number, width: number, height: number): number;
declare function CreateWebUI3D(x: number, y: number, z: number, rx: number, ry: number, rz: number, width: number, height: number, FrameRate: number): number;
declare function SetIgnoreLookInput(bIgnore: boolean): void;
declare function Base64Encode(text: string): string;
//declare function GetPlayerCameraForwardVector(): void;
declare function IsShiftPressed(): boolean;
declare function IsCtrlPressed(): boolean;
//declare function GetObjectLocation(object: number): void;
declare function CreateWebUI(x: number, y: number, width: number, height: number): number;
//declare function CreateWebUI(x: number, y: number, width: number, height: number [, ZOrder, FrameRate]): void;
declare function GetPlayerVehicle(): number;